name: JUnit

on: 
  push:
    branches:
     - master
    paths:
     - 'Backend/**'

jobs:
  junit:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./Backend

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          architecture: x64
      - name: Cambiar a HSQL en persistence
        
        run: |
          powershell
          $path = "src/main/resources/META-INF/persistence.xml"
          [xml] $file = get-content($path)
          #Lo que sigue es por el 'xmlns' (xml namespace)
          $nameSpaceTable = new-object Xml.XmlNamespaceManager $file.NameTable
          $nameSpaceTable.AddNamespace("per", "http://java.sun.com/xml/ns/persistence")
          function with_name{
          	param([string] $name)
          	$file.SelectSingleNode("//per:property[@name='$name']", $nameSpaceTable)
          }
          function hibernate_connection{
          	param([string] $name)
          	with_name("hibernate.connection.$name")
          }
          $node = hibernate_connection("driver_class")
          $node.value="org.hsqldb.jdbcDriver"
          $node = hibernate_connection("url")
          $node.value="jdbc:hsqldb:mem:app-db"
          $node = hibernate_connection("username")
          $node.value="sa"
          $node = hibernate_connection("password")
          $node.value=""
          $node = with_name("hibernate.dialect")
          $node.value="org.hibernate.dialect.HSQLDialect"
          $file.Save($path)
          exit
      - name: Correr Tests
        run: mvn --batch-mode --update-snapshots verify